"use client";
import { useMemo,useState } from "react";
import { Mic,Plus,Save,Trash2 } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { usePreferences } from "./Preferences";
const hiSuggestions=["चीनी","नमक","आटा","चावल","दूध","बिस्किट","मैगी","साबुन","टूथपेस्ट","आइसक्रीम"];
const enSuggestions=["Sugar","Salt","Flour","Rice","Milk","Biscuits","Noodles","Soap","Toothpaste","Ice cream"];
type SpeechRecognitionCtor = new()=>{lang:string;interimResults:boolean;start:()=>void;onresult:(event:{results:ArrayLike<{0:{transcript:string}}>})=>void;onerror:()=>void};
declare global{interface Window{SpeechRecognition?:SpeechRecognitionCtor;webkitSpeechRecognition?:SpeechRecognitionCtor}}
export function ListBuilder(){
 const {language}=usePreferences(); const hi=language==="hi"; const suggestions=hi?hiSuggestions:enSuggestions;
 const [items,setItems]=useState<string[]>([]),[input,setInput]=useState(""),[parentName,setParentName]=useState(""),[phone,setPhone]=useState(""),[note,setNote]=useState(""),[code,setCode]=useState(""),[message,setMessage]=useState("");
 const qrValue=useMemo(()=>code?JSON.stringify({code,items,parentName,phone,note}):"",[code,items,parentName,phone,note]);
 function addItem(value=input){const clean=value.trim();if(!clean)return;setItems(old=>[...old,clean]);setInput("")}
 function listen(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){setMessage(hi?"इस फोन में आवाज़ से लिखना उपलब्ध नहीं है। कीबोर्ड का माइक इस्तेमाल करें।":"Voice input is not available in this browser. Use your keyboard microphone.");return}const r=new R();r.lang=hi?"hi-IN":"en-IN";r.interimResults=false;r.onresult=e=>setInput(e.results[0][0].transcript);r.onerror=()=>setMessage(hi?"आवाज़ समझ नहीं आई। फिर से बोलें।":"We could not understand. Please try again.");r.start()}
 function saveList(){if(!items.length){setMessage(hi?"पहले कम से कम एक सामान जोड़ें।":"Add at least one item first.");return}const newCode=String(Math.floor(1000+Math.random()*9000));localStorage.setItem(`vgs-list-${newCode}`,JSON.stringify({code:newCode,items,parentName,phone,note,createdAt:Date.now()}));setCode(newCode);setMessage(hi?"लिस्ट सेव हो गई। यह कोड बच्चे को भेजें।":"List saved. Send this code to the child.")}
 return <section className="listPanel" id="list"><div className="listIntro"><span className="eyebrow">{hi?"घर की खरीदारी लिस्ट":"Family shopping list"}</span><h2>{hi?"बच्चे सामान भूल जाते हैं?":"Do children forget items?"}</h2><p>{hi?"सामान चुनें, लिखें या बोलें। लिस्ट सेव करें और मिला कोड बच्चे को भेजें।":"Select, type or speak the items. Save the list and send the code to the child."}</p><div className="steps"><span>1. {hi?"सामान जोड़ें":"Add items"}</span><span>2. {hi?"लिस्ट सेव करें":"Save list"}</span><span>3. {hi?"कोड दिखाएं":"Show code"}</span></div></div>
 <div className="builderCard"><div className="suggestions">{suggestions.map(item=><button key={item} onClick={()=>addItem(item)}>{item}<Plus size={14}/></button>)}</div><div className="inputRow"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addItem()} placeholder={hi?"सामान लिखें, जैसे 1 किलो चीनी":"Type an item, e.g. 1 kg sugar"}/><button className="iconBtn" onClick={listen} aria-label="Voice input"><Mic/></button><button className="btn btnGreen" onClick={()=>addItem()}><Plus size={18}/>{hi?"जोड़ें":"Add"}</button></div>
 <div className="itemList">{items.length===0?<p className="empty">{hi?"अभी कोई सामान नहीं जोड़ा गया है।":"No items added yet."}</p>:items.map((item,i)=><div className="item" key={`${item}-${i}`}><span>{i+1}. {item}</span><button onClick={()=>setItems(items.filter((_,index)=>index!==i))} aria-label="Remove"><Trash2 size={17}/></button></div>)}</div>
 <div className="customerFields"><input value={parentName} onChange={e=>setParentName(e.target.value)} placeholder={hi?"माता-पिता का नाम (वैकल्पिक)":"Parent name (optional)"}/><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder={hi?"फोन नंबर (वैकल्पिक)":"Phone number (optional)"}/><input value={note} onChange={e=>setNote(e.target.value)} placeholder={hi?"नोट: सामान न मिले तो फोन करें":"Note: call if an item is unavailable"}/></div>
 <button className="btn btnOrange saveBtn" onClick={saveList}><Save size={19}/>{hi?"लिस्ट सेव करें":"Save list"}</button>{message&&<p className="message">{message}</p>}{code&&<div className="codeCard"><div><small>{hi?"आपकी लिस्ट का कोड":"Your list code"}</small><strong>{code}</strong><p>{hi?"यह कोड दुकान पर दिखाएं।":"Show this code at the store."}</p></div><QRCodeSVG value={qrValue} size={112} fgColor="#0c5c3e"/></div>}</div></section>
}
